version: '2'
services:
  ipfs-daemon:
    image: 'ipfs/kubo:v0.18.1'
    ports:
      - "4001:4001"
      - "5001:5001"
    user: "ipfs"
    command: [ "daemon", "--enable-pubsub-experiment" ]
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mynetwork

  kafka-server:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork

  springapi:
    image: toupk/springapi
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - ipfs-daemon
      - kafka-server

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  
  go-service:
    image: toupk/go-service
    ports:
      - "3336:3336"
    networks:
      - mynetwork
    depends_on:
      - kafka-server
      - mongodb

networks:
  mynetwork:
    driver: bridge
