version: '2'
services:
  ipfs-daemon:
    image: 'ipfs/kubo:v0.18.1'
    ports:
      - "4001:4001"
      - "5001:5001"
    user: "ipfs"
    command: [ "daemon", "--enable-pubsub-experiment" ]
    networks: 
      - mynetwork

  kafka-server:
    image: michaeldqin/kafka
    hostname: kafka-server
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
    - ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092    
    volumes:
    - ${PWD}/.:/opt/kafka_2.12-1.0.0/log
    networks: 
      - mynetwork
      
  springapi:
    image: springapi
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - ipfs-daemon
      - kafka-server

networks:
  mynetwork:
    driver: bridge