version: '2.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mynetwork2

  kafka-server:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork2
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mynetwork2
  
  go-service:
    image: go-service
    build:
      context: .
    ports: 
      - "3336:3336"
    networks:
      - mynetwork2
    depends_on:
      kafka-server:
        condition: service_completed_successfully
      mongodb :
        
    

networks:
  mynetwork2:
    driver: bridge
